---
source:
  is_cloud: false
  verify_ssl: false
  enabled: true
  client_id: ""
  client_secret: ""
  username: ""
  password: ""
  is_free: false
  url: ""
  directories:
    pack: "packs"
    lookups: "lookups"
    configs: "configs"
    certificates: "certificates"
destination:
  is_cloud: false
  client_id: ""
  client_secret: ""
  username: ""
  enabled: true
  is_free: false
  password: ""
  verify_ssl: false
  url: ""