
ALL_IS_WELL = 0
GIT_NOT_FOUND = 1
INVALID_COMMAND_PARAMETERS = 2
DEST_EXISTS = 4
style_NOT_PRESENT = 5
GIT_REPO_ERROR = 6
LOCATION_NOT_FOUND = 7
FILE_NOT_FOUND = 8
SYSTEM_CONFIG_NOT_FOUND = 9
YAML_ERROR = 10
NOT_INIT = 11
CONFIG_NOT_FOUND = 12
INVALID_VALUE = 13
ROOT_CONFIG_NOT_FOUND = 14
ROOT_CONFIG_FOUND = 15
