name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: 3.12
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install build
        - name: 'Get Version'
          id: version
          uses: 'cloudposse/github-action-jq@main'
          with:
            input: 'package.json'
            # JQ query string
            script: '.version'
            # Output raw strings, not JSON texts
            raw-output: true
        - name: 'Get Release Notes'
          id: releaseNotes
          uses: 'cloudposse/github-action-jq@main'
          with:
            input: 'release_notes.json'
            # JQ query string
            script: '.| to_entries[] | select(.key | startswith("${{ steps.version.outputs.output }}")) | .value'
            # Output raw strings, not JSON texts
            raw-output: true
        - name: Tag the commit
          run: |
            next_version=${{ steps.version.outputs.output }}
            git config --global user.email "appsupport@aplura.com"
            git config --global user.name "${{ github.actor }}"
            git tag -a "$next_version" -m "Version $next_version"
            git push --follow-tags
        - name: Build Package SDist
          run: python -m build --sdist
        - name: Build Package Wheel
          run: python -m build --wheel
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          with:
            artifacts: "dist/*"
            tag_name: ${{ steps.version.outputs.output }}
            release_name: Release ${{ steps.version.outputs.output }}
            body: |
              ${{ steps.releaseNotes.outputs.output }}
            draft: false
            prerelease: false